# Generated by Django 5.2.12 on 2026-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('technician', 'Lab Technician'), ('hospital_admin', 'Hospital Admin'), ('platform_admin', 'Platform Admin')], default='doctor', max_length=20),
        ),
    ]
